services:
  - type: web
    name: football-stats-dashboard
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FOOTBALL_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
